### ISSUE TITLE
The errors still exit :(

### ISSUE THREAD

**Issue by lamcrazy** [fletcher/c-sss#11]
Hi all,
I'm sorry that the errors are still existing.
I downloaded the latest version, and used the cmake-gui tool to generate the vs project,but when debuging the project in vs2019, it still display the errrors.

So I guess maybe my steps or my tools could not fit the source code. At the same time, I could not find the directions in the README（except for the "About the Source"） about choosing which tools to run the program and the documentation link is banned. Could you share your tools(softwear) and your steps in deatils about running the source code? Thanks a lot!!!!!!!

![pic1](https://user-images.githubusercontent.com/47603246/88908320-49955800-d28c-11ea-9a83-d74de89bf079.png)
![pic2](https://user-images.githubusercontent.com/47603246/88908336-5023cf80-d28c-11ea-8a98-59c0c18cdb89.png)

_Originally posted by @lamcrazy in https://github.com/fletcher/c-sss/issues/9#issuecomment-666265346_

**Comment by lamcrazy** [comment]
hi，today I used gcc to run the project ,it worked!!!

**Comment by fletcher** [comment]
I don't use Visual Studio,  so can't directly test whether this can be improved with some configuration flags, or if the codebase has to be rewritten in certain places. I don't have the time right now to track down the specific issues with VS.

I'm glad gcc works, and I am certainly open to pull requests to improve compatibility with Visual Studio.
