### ISSUE TITLE
problem about time complexity

### ISSUE THREAD

**Issue by celeste95** [fletcher/c-sss#5]
Thanks for your code and program!
I use your program in the experience of my paper. The function generate_share_strings() takes 1133s to generate share strings of a 1MB text file, but extract_secret_from_share_strings() takes 106s. This is different from what I expected. I created 100 shares and the threshold is 50. 
Does generate_share_strings() take much more time than extract_secret_from_share_strings() ?

**Comment by fletcher** [comment]
I haven't analyzed the time complexity of the functions, but SSS is not really designed for operating on files that large. (Based on what I've read.)

My understanding is that the recommended approach is to encrypt large files with a traditional passphrase using a good encryption algorithm, and then use SSS on the *passphrase* to generate shares.  The shares are then combined to recreate the passphrase, which is then used to decrypt the large file.
