### ISSUE TITLE
memory leak bug in c-sss/src/shamir.c:517 extract_secret_from_share_strings() function

### ISSUE THREAD

**Issue by yunyouxi0** [fletcher/c-sss#7]
line517: the memory malloc by strdup that temp_string ponited is not free

https://github.com/fletcher/c-sss/blob/443953f391e0c23190c4ee18ef38ab3df1ad009d/src/shamir.c#L509-L546

**Comment by fletcher** [comment]
Thanks for reporting this.

Strangely, valgrind didn't seem to find this when I added a new unit test for that function.  Xcode's leak profiler does.  The only other leak it detects is a single one from `arc4_init()`.  I'll have to dig into it, but that one seems to be a one-off no matter how many times `arc4random_uniform()` is called, so it might not be worth too much time at the moment.
